//  darkMode/lightMode switcher - its need to be updated/rewritten
/* 
document.querySelector('#darkModeButton').onclick = function() {

        if (document.getElementById('body').classList.contains('darkMode')) {
            document.getElementById('body').classList.toggle('darkMode');
            for (let i = 0; i < 7; i++) {
                document.getElementById(i).classList.toggle('navLinkDark');
            }
        } else {
            document.getElementById('body').classList.toggle('darkMode');
            for (let i = 0; i < 7; i++) {
                document.getElementById(i).classList.toggle('navLinkDark');
            }
        }
    }
*/

//  Homework - Week III
/*
const name = "User1";
console.log(`Hello World ${name}`);
*/

/* Homework - Week IV
const about = document.querySelector(".about__paragraph--js");
about.innerHTML = "<strong>Hello World! </strong><em>(generated by JS)</em>";
*/

//Homework - Week V
console.log(`Hello, curious person. If you want to say hi, and present yourself go to about.html and type getInformation() Cheers!`);

const getInformation = () => {
    const name = prompt("What's your name? ");
    const age = prompt("How old are you?");
    //console.log(`Welcome ${name}, you are ${age} years old`);

    const displayInformation = document.querySelector(".about__paragraph--js");
    displayInformation.innerHTML = `Welcome <strong>${name}</strong>, you are <strong>${age} </strong> years old`;
}

//Homework - Week VI (hamburger-menu)
const menuSwitcher = document.querySelector('.navigation__switcher--js');
const navigationList = document.querySelector('.navigation__list--js');
menuSwitcher.addEventListener('click', (e) => {
    navigationList.classList.toggle('navigation__list--visible');
    menuSwitcher.classList.toggle('navigation__switcher--exit');
})